[package]
name = "tm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
url = "2.4.0"
dirs = "5.0.1"
toml = "0.7.6"
toml_edit = "0.19.14"
serde = { version = "1.0.178", features = ["derive"] }
anyhow = "1.0.72"
fs_extra = "1.3.0"
semver = { version = "1.0.18", features = ["serde"] }