[package]
name = "tm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.19", features = ["derive"] }
codespan-reporting = "0.11.1"
comfy-table = "7.0.1"
dirs = "5.0.1"
fs_extra = "1.3.0"
semver = { version = "1.0.18", features = ["serde"] }
serde = { version = "1.0.178", features = ["derive"] }
toml = "0.7.6"
walkdir = "2.3.3"